platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "3.5.0-jdk-8"

inputs:
  - name: pipeline-repo
  - name: test-common-repo
  - name: m2

outputs:
  - name: to-push

run:
  path: sh
  args:
    - pipeline-repo/tasks/m2-install-set-repo.sh
